const INBOUND = Object.freeze({
  CREATE_PARTY: 'create_party',
  JOIN_PARTY: 'join_party',
  JOIN_PUBLIC_PARTY: 'join_public_party',
  LEAVE_PARTY: 'leave_party',
  SET_PARTY_VISIBILITY: 'set_party_visibility',
  UPDATE_SETTINGS: 'update_settings',
  START_GAME: 'start_game',
  SET_READY: 'set_ready',
  MAKE_GUESS: 'make_guess',
  NEXT_ROUND: 'next_round',
  REMATCH: 'rematch',
  REQUEST_SETTINGS_CHANGE: 'request_settings_change',
  PLAYER_TYPING: 'player_typing',
  HEARTBEAT: 'heartbeat',
  RECONNECT_ATTEMPT: 'reconnect_attempt',
});

const OUTBOUND = Object.freeze({
  CONNECTED: 'connected',
  PARTY_CREATED: 'party_created',
  PARTY_JOINED: 'party_joined',
  PLAYER_JOINED: 'player_joined',
  PLAYER_LEFT: 'player_left',
  PARTY_LEFT: 'party_left',
  PARTY_CLOSED_HOST_LEFT: 'party_closed_host_left',
  PARTY_VISIBILITY_UPDATED: 'party_visibility_updated',
  SETTINGS_UPDATED: 'settings_updated',
  SETTINGS_CHANGE_STARTED: 'settings_change_started',
  GAME_STARTED: 'game_started',
  PLAYER_READY: 'player_ready',
  SELECTION_TIMER: 'selection_timer',
  PLAYING_STARTED: 'playing_started',
  GUESS_RESULT: 'guess_result',
  OPPONENT_GUESSED: 'opponent_guessed',
  PLAYER_FINISHED: 'player_finished',
  OPPONENT_FINISHED_FIRST: 'opponent_finished_first',
  WAITING_FOR_OPPONENT: 'waiting_for_opponent',
  ROUND_ENDED: 'round_ended',
  NEXT_ROUND_STARTED: 'next_round_started',
  REMATCH_REQUESTED: 'rematch_requested',
  REMATCH_STARTED: 'rematch_started',
  PLAYER_TYPING: 'player_typing',
  PLAYER_DISCONNECTED: 'player_disconnected',
  PLAYER_RECONNECTED: 'player_reconnected',
  RECONNECTED: 'reconnected',
  RECONNECT_FAILED: 'reconnect_failed',
  PROFILE_UPDATED: 'profile_updated',
  LEADERBOARD_UPDATED: 'leaderboard_updated',
  PUBLIC_DIRECTORY_UPDATED: 'public_directory_updated',
  ERROR: 'error',
});

module.exports = Object.freeze({
  INBOUND,
  OUTBOUND,
});
